"use client";

import { FormEvent, useState } from "react";
import { LandingPage, LandingSection, asItems, asText } from "@/lib/landing-pages";
import MetaPixel from "@/components/meta-pixel";

function trackMetaEvent(eventName: string) {
    const win = window as Window & { fbq?: (...args: unknown[]) => void };
    win.fbq?.("track", eventName);
}

function buttonStyle(primary = true): React.CSSProperties {
    return { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "13px 18px", borderRadius: 8, border: primary ? "1px solid #102536" : "1px solid #c8d3d0", background: primary ? "#102536" : "transparent", color: primary ? "#fff" : "#102536", fontWeight: 700, fontSize: 13, textDecoration: "none", cursor: "pointer" };
}

function Section({ section, onLead }: { section: LandingSection; onLead?: () => void }) {
    const content = section.content;
    const items = asItems(content.items);
    const heading = asText(content.heading);
    const body = asText(content.body);
    if (section.section_type === "hero") return <section style={{ padding: "110px 0 85px", display: "grid", gridTemplateColumns: "minmax(0,1.1fr) minmax(280px,.8fr)", gap: 46, alignItems: "center" }}><div><p style={{ color: "#7da746", fontSize: 11, fontWeight: 800, letterSpacing: ".14em", margin: "0 0 18px" }}>{asText(content.eyebrow)}</p><h1 style={{ color: "#102536", fontSize: "clamp(42px,6vw,78px)", lineHeight: .98, letterSpacing: "-.06em", margin: 0, maxWidth: 700 }}>{asText(content.heading, "Your next campaign starts here.")}</h1><p style={{ color: "#587082", fontSize: 18, lineHeight: 1.65, maxWidth: 620, margin: "26px 0 28px" }}>{asText(content.body)}</p><div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}><a href={asText(content.primary_cta_url, "#lead-form")} onClick={onLead} style={buttonStyle()}>{asText(content.primary_cta_label, "Get started")}</a>{asText(content.secondary_cta_label) && <a href={asText(content.secondary_cta_url, "#features")} style={buttonStyle(false)}>{asText(content.secondary_cta_label)}</a>}</div></div><div style={{ minHeight: 340, borderRadius: 22, background: "#102536", padding: 24, boxShadow: "0 24px 55px rgba(16,37,54,.18)" }}><div style={{ display: "flex", justifyContent: "space-between", color: "#bde87a", fontSize: 11, letterSpacing: ".08em" }}><span>LIVE CAMPAIGN</span><span>●</span></div><div style={{ marginTop: 70, color: "#fff", fontSize: 28, fontWeight: 700, letterSpacing: "-.04em" }}>{asText(content.heading, "A clearer next step")}</div><div style={{ marginTop: 20, height: 10, borderRadius: 99, background: "#9cc653", width: "72%" }} /><div style={{ marginTop: 12, height: 10, borderRadius: 99, background: "#395267", width: "88%" }} /><div style={{ marginTop: 48, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><div style={{ background: "#203b50", borderRadius: 12, padding: 14, color: "#fff" }}><small style={{ color: "#a8bdc8" }}>Leads</small><strong style={{ display: "block", marginTop: 5, fontSize: 24 }}>+128</strong></div><div style={{ background: "#203b50", borderRadius: 12, padding: 14, color: "#fff" }}><small style={{ color: "#a8bdc8" }}>Next step</small><strong style={{ display: "block", marginTop: 5, fontSize: 15 }}>Ready</strong></div></div></div></section>;
    if (section.section_type === "features") return <section id="features" style={{ padding: "76px 0" }}><p style={{ color: "#7da746", fontSize: 11, fontWeight: 800, letterSpacing: ".14em" }}>{asText(content.eyebrow, "THE VALUE")}</p><h2 style={{ color: "#102536", fontSize: "clamp(30px,4vw,52px)", lineHeight: 1.02, letterSpacing: "-.05em", margin: "10px 0 12px" }}>{heading}</h2><p style={{ color: "#587082", maxWidth: 620, lineHeight: 1.6 }}>{body}</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14, marginTop: 30 }}>{items.map((item, index) => <div key={index} style={{ border: "1px solid #d7e0dd", borderRadius: 14, padding: 22, background: "#fff" }}><div style={{ width: 32, height: 32, borderRadius: 9, background: "#eaf4d9", color: "#628d2b", display: "grid", placeItems: "center", fontWeight: 800 }}>{String(index + 1).padStart(2, "0")}</div><h3 style={{ color: "#102536", fontSize: 16, margin: "18px 0 8px" }}>{item.title}</h3><p style={{ color: "#587082", fontSize: 13, lineHeight: 1.55, margin: 0 }}>{item.body}</p></div>)}</div></section>;
    if (section.section_type === "proof") return <section style={{ padding: "70px 0", borderTop: "1px solid #d7e0dd", borderBottom: "1px solid #d7e0dd" }}><blockquote style={{ maxWidth: 880, margin: "0 auto", textAlign: "center", color: "#102536", fontSize: "clamp(24px,3vw,40px)", lineHeight: 1.2, letterSpacing: "-.04em" }}>“{asText(content.quote)}”</blockquote><p style={{ textAlign: "center", color: "#587082", fontSize: 13, marginTop: 22 }}>{asText(content.name)} · {asText(content.role)}</p></section>;
    if (section.section_type === "pricing") return <section style={{ padding: "76px 0", textAlign: "center" }}><h2 style={{ color: "#102536", fontSize: 38, letterSpacing: "-.04em", margin: 0 }}>{heading}</h2><p style={{ color: "#587082", margin: "12px auto 25px", maxWidth: 560 }}>{body}</p><div style={{ maxWidth: 390, margin: "0 auto", border: "1px solid #d7e0dd", borderRadius: 16, padding: 28, background: "#fff", textAlign: "left" }}><p style={{ color: "#7da746", fontWeight: 800, fontSize: 11, letterSpacing: ".12em" }}>{asText(content.label, "START HERE")}</p><div style={{ color: "#102536", fontSize: 42, fontWeight: 800, letterSpacing: "-.05em", margin: "10px 0" }}>{asText(content.price, "Custom")}</div><p style={{ color: "#587082", fontSize: 13 }}>{asText(content.detail, "A focused plan for your next stage.")}</p><a href={asText(content.cta_url, "#lead-form")} onClick={onLead} style={{ ...buttonStyle(), width: "100%", marginTop: 12 }}>{asText(content.cta_label, "Get started")}</a></div></section>;
    if (section.section_type === "faq") return <section style={{ padding: "70px 0" }}><h2 style={{ color: "#102536", fontSize: 36, letterSpacing: "-.04em", margin: 0 }}>{heading}</h2><div style={{ display: "grid", gap: 10, marginTop: 24 }}>{items.map((item, index) => <details key={index} style={{ border: "1px solid #d7e0dd", borderRadius: 10, padding: "15px 17px", background: "#fff" }}><summary style={{ color: "#102536", fontWeight: 700, cursor: "pointer" }}>{item.question || item.title}</summary><p style={{ color: "#587082", fontSize: 13, lineHeight: 1.6, margin: "12px 0 0" }}>{item.answer || item.body}</p></details>)}</div></section>;
    if (section.section_type === "logos") return <section style={{ padding: "38px 0", borderTop: "1px solid #d7e0dd", borderBottom: "1px solid #d7e0dd" }}><p style={{ textAlign: "center", color: "#8a9aa2", fontSize: 11, letterSpacing: ".12em", fontWeight: 800 }}>{asText(content.heading, "TRUSTED BY TEAMS MOVING FORWARD")}</p><div style={{ display: "flex", justifyContent: "center", gap: 28, flexWrap: "wrap", color: "#587082", fontWeight: 700, marginTop: 20 }}>{items.map((item, index) => <span key={index}>{item.name || item.title}</span>)}</div></section>;
    if (section.section_type === "lead_form") return <LeadForm content={content} onLead={onLead} />;
    return <section style={{ padding: "70px 30px", borderRadius: 18, background: "#dff0bd", textAlign: "center", margin: "30px 0" }}><h2 style={{ color: "#102536", fontSize: 36, letterSpacing: "-.04em", margin: 0 }}>{heading}</h2><p style={{ color: "#587082", maxWidth: 560, margin: "12px auto 24px" }}>{body}</p><a href={asText(content.button_url, "#lead-form")} onClick={onLead} style={buttonStyle()}>{asText(content.button_label, "Get started")}</a></section>;
}

function LeadForm({ content, onLead }: { content: Record<string, unknown>; onLead?: () => void }) {
    const [form, setForm] = useState({ name: "", email: "", company_name: "", job_title: "", website: "" });
    const [message, setMessage] = useState("");
    const [saving, setSaving] = useState(false);
    async function submit(event: FormEvent) {
        event.preventDefault(); setSaving(true); setMessage(""); onLead?.();
        const params = new URLSearchParams(window.location.search);
        const response = await fetch("/api/leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, page_slug: params.get("page") || window.location.pathname.replace(/^\/p\//, "") || "landing-page", utm_source: params.get("utm_source") || "", utm_medium: params.get("utm_medium") || "", utm_campaign: params.get("utm_campaign") || "" }) });
        const body = await response.json();
        setMessage(response.ok ? asText(content.success_message, "Thanks — we will be in touch shortly.") : body.error || "Please try again.");
        if (response.ok) trackMetaEvent("Lead");
        if (response.ok) setForm({ name: "", email: "", company_name: "", job_title: "", website: "" });
        setSaving(false);
    }
    return <section id="lead-form" style={{ padding: "76px 0", display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(300px,.8fr)", gap: 35, alignItems: "start" }}><div><h2 style={{ color: "#102536", fontSize: 42, letterSpacing: "-.05em", margin: 0 }}>{asText(content.heading, "Get the next step.")}</h2><p style={{ color: "#587082", lineHeight: 1.6, marginTop: 14, maxWidth: 520 }}>{asText(content.body)}</p></div><form onSubmit={submit} style={{ display: "grid", gap: 10, padding: 22, border: "1px solid #d7e0dd", borderRadius: 14, background: "#fff" }}><input required placeholder="Your name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} style={{ padding: 12, border: "1px solid #c8d3d0", borderRadius: 8 }} /><input required type="email" placeholder="Work email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} style={{ padding: 12, border: "1px solid #c8d3d0", borderRadius: 8 }} /><input placeholder="Company" value={form.company_name} onChange={event => setForm({ ...form, company_name: event.target.value })} style={{ padding: 12, border: "1px solid #c8d3d0", borderRadius: 8 }} /><input placeholder="Job title" value={form.job_title} onChange={event => setForm({ ...form, job_title: event.target.value })} style={{ padding: 12, border: "1px solid #c8d3d0", borderRadius: 8 }} /><input aria-hidden="true" tabIndex={-1} autoComplete="off" value={form.website} onChange={event => setForm({ ...form, website: event.target.value })} style={{ position: "absolute", left: "-10000px", opacity: 0 }} /><button disabled={saving} type="submit" style={buttonStyle()}>{saving ? "Sending…" : asText(content.button_label, "Send request")}</button>{message && <p role="status" style={{ margin: 2, color: "#587082", fontSize: 12 }}>{message}</p>}</form></section>;
}

export default function PublicLandingPage({ page }: { page: LandingPage }) {
    return <main style={{ minHeight: "100vh", background: "#f6f8f4", color: "#102536", fontFamily: "Arial, sans-serif" }}><MetaPixel /><div style={{ maxWidth: 1180, margin: "0 auto", padding: "0 28px" }}><header style={{ height: 74, display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid #d7e0dd" }}><strong style={{ fontSize: 18, letterSpacing: "-.03em" }}>{page.name}</strong><a href="#lead-form" style={buttonStyle(false)}>Get started ↗</a></header>{page.sections.slice().sort((a, b) => a.sort_order - b.sort_order).map((section, index) => <Section key={section.id || index} section={section} />)}<footer style={{ padding: "35px 0 45px", color: "#8a9aa2", fontSize: 11, borderTop: "1px solid #d7e0dd" }}>© {new Date().getFullYear()} {page.name}</footer></div></main>;
}
